### ISSUE TITLE
`transaction.outputs[1].capacity must be a hex integer` when transferring

### ISSUE THREAD

**Issue by homura** [zhangyouxin/demo-nexus#11]
![image](https://user-images.githubusercontent.com/7511174/228113307-70e1b92e-bead-40b7-ba8e-18615e11adbc.png)

**Comment by zhangyouxin** [comment]
@homura Hi, I think this issue is resolved by #14, can you briefly check it here: 
https://demo-nexus-2euq831gd-zhangyouxin.vercel.app/
