### ISSUE TITLE
Feature request: a description for send

### ISSUE THREAD

**Issue by homura** [zhangyouxin/demo-nexus#4]
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/7511174/223474474-f723f3eb-5828-4bf3-a21f-18b95b6d8e95.png">

<img width="765" alt="image" src="https://user-images.githubusercontent.com/7511174/223474610-3eaa4edd-21b1-4c3e-b599-e434a92e45ef.png">

Some of the UTxO wallet will have a description when transfer to another, if the Nexus demo also has a description that would be cool

**Comment by zhangyouxin** [comment]
closed by https://github.com/zhangyouxin/demo-nexus/pull/7
